### ISSUE TITLE
[Bug]: opencomic don't load Big Cbr files

### ISSUE THREAD

**Issue by Duke715** [ollm/OpenComic#339]
### Preflight Checklist

- [x] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.4.1

### Operating System

windows 11

### Installed via

.exe

### Steps to reproduce

opencomic is not able to load big cbr files... 

### Expected Behavior

i expect to open big files

### Actual Behavior

opencomic crash when i try to open big files

**Comment by ollm** [comment]
Thanks for reporting!

It seems to be a problem with the `node-unrar-js` library used in OpenComic.

I'll try to see if I can reproduce the error locally.

**Comment by Duke715** [comment]
i hope you solve this because i like opencomic very much

**Comment by ollm** [comment]
How big are the files? I've tried a 6GB one and although it takes a while to open it, it doesn't crash.

If possible, could you send me any of the files to my email? oleguer.llopart.mora@gmail.com

**Comment by Duke715** [comment]
the file is 1.4 GB......i can't send u via mail because is too big but the structure is 11 folders with pictures 700kb average.
I'm using gonvisor also to open comics and it's superfast to open big files.
i would like to open directly fullscreen without the toolbar on top....thx for your great work

**Comment by ollm** [comment]
> the file is 1.4 GB......i can't send u via mail because is too big but the structure is 11 folders with pictures 700kb average.

I have tried it with a similar rar file and I have not been able to reproduce it.

When you say that OpenComic crashes, does the app close or is it still open?

- If it is still open, can you check the console for errors? `Debbug > Toogle DevTools`
- If app closes, you can try running OpenComic from **Command Prompt** and see if any errors appear when the app crashes `C:\Users\<YouUserName>\AppData\Local\Programs\OpenComic\OpenComic.exe`

> i can't send u via mail

Can you send the file via mail with a link in Google Drive, Dropbox, Mega, etc?

> i would like also to open directly fullscreen without the toolbar on top....thx for your great work

This is a bug and I just fixed it here 7dbc3c297f7d92aa209ca8bf901368e47b63e3a3, try this buid:

Build: https://mega.nz/file/CXBlUJhK#sr_4f9b1NsEJGWckRnHLpT96AJRwT0j1qiXwES95Gtc

**Comment by Duke715** [comment]
i can't do nothing.....the software is still open but i can't use the toolbar....it's frozen
thx for the new build.....thx for your work

**Comment by Duke715** [comment]
The new build won't solve the full screen problem plus i can't use the black theme...

**Comment by ollm** [comment]
You can try to disable image interpolation, and then try to open the cbr again, it may be related to https://github.com/ollm/OpenComic/issues/315

![Captura de pantalla 2025-01-07 161907](https://github.com/user-attachments/assets/4d2cde97-e814-4eb9-84e4-5ce44d9cc2ec)

If it still happens, do you have WinRAR installed? If so, with WinRAR you can see what characteristics the compressed file has (Dictionary size, RAR version, etc.) by following the steps below.

`Open WinRAR > Drag some of the files > Tools > Show information`

Example: 

![Image](https://github.com/user-attachments/assets/b0e95f68-8be7-44dd-9ac6-658c09358d43)

> The new build don't solve the full screen problem

You may not have the header bar disabled from the 3 dot menu, you have to do that when you are in full screen mode, as it can be disabled separately (In full screen and without it)

![Image](https://github.com/user-attachments/assets/fe92fb75-37b0-4ac1-9bb7-243e5c488a25)

**Comment by Duke715** [comment]
i solved the problem simply changing the extension from cbz to cbr.
for the full screen issue i hide the header bar but when i open the file i still see the bar with file debug etc..

**Comment by ollm** [comment]
Sorry, I think I did the build without the fix applied.

In this build there are also some changes to improve file detection, it may fix the problem with rar files without changing the extension.

- Upd: Detect binary fromFile to fromBuffer c006bd21d6342678de7420fceec863f7a36ffc56 
- Fix: Disable rar object cache 56763806c564f90897b5b0f9be6c2a80590e3b02

Build: https://mega.nz/file/eTBWzDCb#b1RCA9b4KfM9X4nHpqtB5nUp1lFnYnKsm7ecNdnCs04

**Comment by Duke715** [comment]
It works great....wow.....thank you very much....great software!!!!
if i find some other issue i will write you again heheeh

**Comment by ollm** [comment]
Closing this, since the fix is now available in [`v1.6.0`](https://opencomic.app/docs/installation/download)
