### ISSUE TITLE
[Bug]: Can't remove library folder

### ISSUE THREAD

**Issue by MarkJeronimus** [ollm/OpenComic#463]
### Preflight Checklist

- [x] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.6.2

### Operating System

LinuxMint

### Installed via

.deb

### Steps to reproduce

Right-click on the library folder

### Expected Behavior

Expect a context menu.

In fact, if I add another folder, I can right click it and delete it, but even with multiple folders present, I cannot delete the one I want to delete.

### Actual Behavior

<img width="2158" height="1190" alt="Image" src="https://github.com/user-attachments/assets/f7b76d68-3f04-4563-a431-a15f1b21086b" />

### Error message

<dt-small-bubble class="console-message-repeat-count" aria-label="Error, Repeated 6 times" style="box-sizing: border-box; min-width: 0px; min-height: 0px; margin: 1.4px 0px 0px 10px; flex: 0 0 auto; color: rgb(31, 31, 31); font-family: &quot;Noto Sans Mono&quot;, &quot;DejaVu Sans Mono&quot;, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(211, 227, 253); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="error" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: inline-flex; height: 14px; align-items: center; vertical-align: middle; white-space: nowrap; padding: 1px 4px; text-align: left; font-size: 11px; line-height: normal; font-weight: bold; text-shadow: none; color: rgb(242, 242, 242); border-radius: 7px; background-color: rgb(220, 54, 46);">6</div></dt-small-bubble><div class="console-message repeated-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 4px; flex: 1 1 auto; display: flex; color: rgb(31, 31, 31); font-family: &quot;Noto Sans Mono&quot;, &quot;DejaVu Sans Mono&quot;, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(211, 227, 253); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 0%; display: flex; flex-direction: row; align-items: flex-start; margin-top: -1px;"><div class="console-message-stack-trace-wrapper" aria-label="/opt/OpenComic/resou…cripts/cache.js:394 Uncaught (in promise) Error: incomplete frame
    at Object.readJson (/opt/OpenComic/resou…pts/cache.js:394:34)
    at file.readCompressed (/opt/OpenComic/resou…e-manager.js:226:20)
    at file.read (/opt/OpenComic/resou…le-manager.js:70:24)
    at _countPages (/opt/OpenComic/resou…/progress.js:139:27)
    at _countPages (/opt/OpenComic/resou…/progress.js:151:19)
    at async _countPages (/opt/OpenComic/resou…/progress.js:151:13)
    at async _countPages (/opt/OpenComic/resou…/progress.js:151:13)
    at async _countPages (/opt/OpenComic/resou…/progress.js:151:13)
    at async countPages (/opt/OpenComic/resou…/progress.js:179:16)
    at async Object.get (/opt/OpenComic/resou…g/progress.js:87:21) Stack table expanded" style="box-sizing: border-box; min-width: 0px; min-height: 0px; --override-display-stack-preview-toggle-link: none; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><devtools-icon role="presentation" name="triangle-down" class="console-message-expand-icon" style="flex-grow: 0; flex-shrink: 0; display: inline-block; width: 14px; height: 14px; color: rgb(71, 71, 71); vertical-align: baseline; position: relative; box-sizing: border-box; min-width: 0px; min-height: 0px; margin-bottom: -4px;"><span style="display: block; width: 14px; height: 14px; background-color: currentcolor; mask: url(&quot;devtools://devtools/bundled/Images/triangle-down.svg&quot;) 50% 50% / contain no-repeat; --icon-url: url(&quot;devtools://devtools/bundled/Images/triangle-down.svg&quot;);"></span></devtools-icon><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: &quot;Noto Sans Mono&quot;, &quot;DejaVu Sans Mono&quot;, monospace; white-space: pre-wrap; font-size: 11px !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="/opt/OpenComic/resources/app.asar/scripts/cache.js:394" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; color: rgb(11, 87, 208); text-decoration: underline; outline-offset: 2px; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; background: none; flex: 0 0 auto; white-space: nowrap; cursor: pointer; outline: none; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">/opt/OpenComic/resou<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>cripts/cache.js:394</button> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(65, 14, 11) !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: &quot;Noto Sans Mono&quot;, &quot;DejaVu Sans Mono&quot;, monospace; white-space: pre-wrap; font-size: 11px !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">Error: incomplete frame
<span class="formatted-stack-frame" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Object.readJson (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="/opt/OpenComic/resources/app.asar/scripts/cache.js:394:34" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; color: rgb(11, 87, 208); text-decoration: underline; outline-offset: 2px; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; background: none; flex: 0 0 auto; white-space: nowrap; cursor: pointer; outline: none; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">/opt/OpenComic/resou<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>pts/cache.js:394:34</button>)
</span><span class="formatted-stack-frame" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at file.readCompressed (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="/opt/OpenComic/resources/app.asar/scripts/file-manager.js:226:20" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; color: rgb(11, 87, 208); text-decoration: underline; outline-offset: 2px; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; background: none; flex: 0 0 auto; white-space: nowrap; cursor: pointer; outline: none; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">/opt/OpenComic/resou<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>e-manager.js:226:20</button>)
</span><span class="formatted-stack-frame" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at file.read (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="/opt/OpenComic/resources/app.asar/scripts/file-manager.js:70:24" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; color: rgb(11, 87, 208); text-decoration: underline; outline-offset: 2px; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; background: none; flex: 0 0 auto; white-space: nowrap; cursor: pointer; outline: none; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">/opt/OpenComic/resou<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>le-manager.js:70:24</button>)
</span><span class="formatted-stack-frame" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at _countPages (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="/opt/OpenComic/resources/app.asar/scripts/reading/progress.js:139:27" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; color: rgb(11, 87, 208); text-decoration: underline; outline-offset: 2px; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; background: none; flex: 0 0 auto; white-space: nowrap; cursor: pointer; outline: none; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">/opt/OpenComic/resou<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>/progress.js:139:27</button>)
</span><span class="formatted-stack-frame" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at _countPages (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="/opt/OpenComic/resources/app.asar/scripts/reading/progress.js:151:19" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; color: rgb(11, 87, 208); text-decoration: underline; outline-offset: 2px; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; background: none; flex: 0 0 auto; white-space: nowrap; cursor: pointer; outline: none; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">/opt/OpenComic/resou<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>/progress.js:151:19</button>)
</span><span class="formatted-stack-frame" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async _countPages (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="/opt/OpenComic/resources/app.asar/scripts/reading/progress.js:151:13" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; color: rgb(11, 87, 208); text-decoration: underline; outline-offset: 2px; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; background: none; flex: 0 0 auto; white-space: nowrap; cursor: pointer; outline: none; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">/opt/OpenComic/resou<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>/progress.js:151:13</button>)
</span><span class="formatted-stack-frame" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async _countPages (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="/opt/OpenComic/resources/app.asar/scripts/reading/progress.js:151:13" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; color: rgb(11, 87, 208); text-decoration: underline; outline-offset: 2px; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; background: none; flex: 0 0 auto; white-space: nowrap; cursor: pointer; outline: none; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">/opt/OpenComic/resou<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>/progress.js:151:13</button>)
</span><span class="formatted-stack-frame" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async _countPages (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="/opt/OpenComic/resources/app.asar/scripts/reading/progress.js:151:13" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; color: rgb(11, 87, 208); text-decoration: underline; outline-offset: 2px; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; background: none; flex: 0 0 auto; white-space: nowrap; cursor: pointer; outline: none; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">/opt/OpenComic/resou<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>/progress.js:151:13</button>)
</span><span class="formatted-stack-frame" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async countPages (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="/opt/OpenComic/resources/app.asar/scripts/reading/progress.js:179:16" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; color: rgb(11, 87, 208); text-decoration: underline; outline-offset: 2px; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; background: none; flex: 0 0 auto; white-space: nowrap; cursor: pointer; outline: none; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">/opt/OpenComic/resou<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>/progress.js:179:16</button>)
</span><span class="formatted-stack-frame" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async Object.get (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="/opt/OpenComic/resources/app.asar/scripts/reading/progress.js:87:21" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; color: rgb(11, 87, 208); text-decoration: underline; outline-offset: 2px; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; background: none; flex: 0 0 auto; white-space: nowrap; cursor: pointer; outline: none; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">/opt/OpenComic/resou<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>g/progress.js:87:21</button>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><div class="vbox flex-auto monospace stack-preview-container width-constrained" style="display: inline-block; width: 495.729px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: &quot;Noto Sans Mono&quot;, &quot;DejaVu Sans Mono&quot;, monospace; font-size: 11px !important; position: relative; flex-direction: column !important; flex: 1 1 auto;"><div class="widget" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; flex: 1 1 auto; contain: style;">
  | readJson | @ | /opt/OpenComic/resou…cripts/cache.js:394
-- | -- | -- | --
  | readCompressed | @ | /opt/OpenComic/resou…file-manager.js:226
  | read | @ | /opt/OpenComic/resou…/file-manager.js:70
  | _countPages | @ | /opt/OpenComic/resou…ing/progress.js:139
  | _countPages | @ | /opt/OpenComic/resou…ing/progress.js:151
  | await in _countPages |   |  
  | _countPages | @ | /opt/OpenComic/resou…ing/progress.js:151
  | await in _countPages |   |  
  | _countPages | @ | /opt/OpenComic/resou…ing/progress.js:151
  | await in _countPages |   |  
  | _countPages | @ | /opt/OpenComic/resou…ing/progress.js:151
  | await in _countPages |   |  
  | countPages | @ | /opt/OpenComic/resou…ing/progress.js:179
  | get | @ | /opt/OpenComic/resou…ding/progress.js:87
  | await in get |   |  
  | comicContextMenu | @ | /opt/OpenComic/resou…scripts/dom.js:2386
  | oncontextmenu | @ | index.html:1

</div></div></div></div></div></div>

**Comment by mooglestiltzkin** [comment]
i added a location from NAS to library, but it doesn't open them properly. so i wanted to remove the location from library (not delete the contents, just simply remove it from showing in the opencomic library).

But i am unable to do so.

**Comment by ollm** [comment]
This should fix this error b3a6bbf012beaca669839594675c8faac55d8085 and should let you remove the library folder.

Build .deb: https://mega.nz/file/zKBBgJ4a#Y_tq7-jjB-AlV0MaqqvYNuh5f08-m8oDo82I9V9W76o

@mooglestiltzkin do you have the same error message, or is it different?

**Comment by mooglestiltzkin** [comment]
@ollm not sure about the errors the TS mentioned, but mine is i added a NAS share location to library. Though it listed, i cannot open any of the compressed rar or zip files to read the manga.

But when i added a network drive for that nas folder location, that worked.

So, i wanted to remove the previously added library but to my shock, there is no way to remove it. I assumed right clicking would have a remove option, but there was nothing. There was a delete option, but that DELETED THE ACTUAL FILE, which is not what i wanted. I just want to remove it from library in opencomic. Not delete the actual folder/file ^^;

Thats my bug to report.

**Comment by mooglestiltzkin** [comment]
i uninstalled, reinstalled.

I notice the default library when u right click does have a remove.

but oddly, when i add a library location myself, that does not have a right click remove.

So my solution was to uninstall. remove the saves configurations. Then reinstall. then add the network drive folder which does work. Still cant remove but at least for that library location added it works.

So the bug still exists

**Comment by MarkJeronimus** [comment]
For me, all folders I add are from the same NAS share, which is an sshfs mount. Only "Manga" cannot be removed, all other folders I add from the same share can, so it's not purely a "how it's mapped" issue.

I can confirm the fix in https://github.com/ollm/OpenComic/commit/b3a6bbf012beaca669839594675c8faac55d8085 works. I was able to remove the library folder. Thanks for always providing an installer with such short turnaround. I know of no other FOSS project that does that.

**Comment by mooglestiltzkin** [comment]
for me the location i added that points to truenas is

`\\GUTS\Storage\Pictures\Manga`

using that, though it indexes in opencomic when you add to library, opening any of the compressed zip/rar/7zip will get frozen when you attempt to open the file.

but, if you go to windows 11, right click on my computer, and add that location as a mounted drive e.g. drive letter P. then you add it to library

`P:\`

This works fine.

This is the first bug. And this is the temporary work around.


For the 2nd bug, as mentioned, the default library folder when doing fresh install, when you right click that, there is a REMOVE option. But after i REMOVED (not delete) that folder from library, and add my own, that right click remove option is no longer available. That is a bug.


`I can confirm the fix in b3a6bbf works. I was able to remove the library folder. Thanks for always providing an installer with such short turnaround. I know of no other FOSS project that does that.`

not sure how to apply that fix to opencomic. sorry i'm newb haha. i only know to download the exe installer file and use that. should i wait for the new release to test if the fix works?

**Comment by MarkJeronimus** [comment]
> not sure how to apply that fix to opencomic. sorry i'm newb haha. i only know to download the exe installer file and use that. should i wait for the new release to test if the fix works?

.deb is like .msi for Debian-flavored Linux

**Comment by ollm** [comment]
> for me the location i added that points to truenas is
> 
> `\\GUTS\Storage\Pictures\Manga`
> 
> using that, though it indexes in opencomic when you add to library, opening any of the compressed zip/rar/7zip will get frozen when you attempt to open the file.
> 
> but, if you go to windows 11, right click on my computer, and add that location as a mounted drive e.g. drive letter P. then you add it to library

It seems there's an error when opening the file, you can check the console to see if there's any error there `Debug` > `Toogle DevTools`

> For the 2nd bug, as mentioned, the default library folder when doing fresh install, when you right click that, there is a REMOVE option. But after i REMOVED (not delete) that folder from library, and add my own, that right click remove option is no longer available. That is a bug.

Are you adding the files through a master folder?
The option to remove only appears if the file or folder has been added to the library individually, for example, by drag and drop or by using the add button.
It doesn't currently work for master folders.

> not sure how to apply that fix to opencomic. sorry i'm newb haha. i only know to download the exe installer file and use that. should i wait for the new release to test if the fix works?

I'm leaving you a master build for Windows: https://mega.nz/file/LLhDxQJJ#uSAGp0VQotj-wXv-gz1Lsf75rVVQMu8CreoewMyhszc

**Comment by mooglestiltzkin** [comment]
For the 2nd issue. No i am not using master folder method. I used the add library individually via the add button. No i didn't drag drop.

When u go to library, then you click add, then it shows the location. So i browse to my truenas location i mentioned, add that. It indexes, but it cannot open any compressed file then it freezes/locks up. Basically i have to open task manager to close opencomic because it's bugs out critically.

But as i said, the temp work around, is to make a drive letter mount for the location where i store the manga on truenas, then go library add, and point it to that drive letter that is now mounted to windows 11. This works fine.

The only thing that still remains a big issue is unable to remove library added. Which is the 1st issue i mentioned.

im helping test the master build u sent. will report back the result

i delete opencomic and also the roaming opencomic so i can test the new master build u uploaded so we got a fresh install to test from.

PS: not sure if this matters but i usually install opencomic via UniGETUI using chocolatey or winget. But i did check the version it was 1.6.2

**Comment by mooglestiltzkin** [comment]
Just wanted to report, i can now remove the library i added, that was using the truenas guts location.

But it's weird. Because, right click the pepper default library, it easily pops up the menu for remove. But for the library i added, it's not 100%. it will pop up maybe, but when i try to repeatedly right click, it also MAY NOT show the menu for the remove library option.

So in the end i try to go into library, then go back, then try right click again.

Anyway that works (sort of)

*update

After i remove the library, then re add back, the remove option seems more reliable. Donno whats up with that, but this seems to work. probably can consider it fixed

https://i.imgur.com/k9X1EQW.jpeg

**Comment by mooglestiltzkin** [comment]
For the frozen bug when trying to open a comic which is a compressed format, this is what that looks like

https://i.imgur.com/wYxrB00.jpeg


I also used devtools like u asked, this is what it showed for the red critical error log

https://i.imgur.com/R0fQAGE.jpeg



For the record, when opening the same file, but if added as a library as a mounted drive letter for windows 11, this works fine with no issue. It's only if you add  the location i mentioned previously for truenas directly, would it go crazy x-x;

So unless there is a fix for that, maybe a note for people in this situation as a temporary workaround, is to mount the manga folder location as a mounted drive, then add that as a library. because that will work. You don't necessarily need to mount the manga/media folder directly, but it has to be browesable from a mounted drive letter.

**Comment by gsxgmpkt9020** [comment]
> For the frozen bug when trying to open a comic which is a compressed format, this is what that looks like
> 
> https://i.imgur.com/wYxrB00.jpeg
> 
> I also used devtools like u asked, this is what it showed for the red critical error log
> 
> https://i.imgur.com/R0fQAGE.jpeg
> 
> For the record, when opening the same file, but if added as a library as a mounted drive letter for windows 11, this works fine with no issue. It's only if you add the location i mentioned previously for truenas directly, would it go crazy x-x;
> 
> So unless there is a fix for that, maybe a note for people in this situation as a temporary workaround, is to mount the manga folder location as a mounted drive, then add that as a library. because that will work. You don't necessarily need to mount the manga/media folder directly, but it has to be browesable from a mounted drive letter.

I can confirm in OpenComic Setup 1.6.2.master.b9cb5ea, I cannot open any files on 192.168.X.X INCLUDING IMAGE FOLDERS, EVERYTHING WILL BE FROZEN.

No errors in devtools because it is frozen too.

![Image](https://github.com/user-attachments/assets/6ddc7d3e-171f-4b66-a7e9-ef3d99b39e70)
![Image](https://github.com/user-attachments/assets/cef7799c-ca11-42b3-b6cb-d97032917a74)

> just to add onto this. i use a truenas server. i couldnt get smb to work. and simply adding the location to the truenas folder location, though it will index into library, the comics in zipped file cannot be opened.
> 
> solution: was to create a network drive. Go to windows 11, right click my computer, select add map network drive. Once done, go to library, then add the network drive you added which now uses a drive letter e.g. X: then it will index and now it works when you try to view a comic. This is one solution to get it to work. 

 _Originally posted by @mooglestiltzkin in [#437](https://github.com/ollm/OpenComic/issues/437#issuecomment-3313782008)_

**Comment by ollm** [comment]
> Just wanted to report, i can now remove the library i added, that was using the truenas guts location.
> 
> But it's weird. Because, right click the pepper default library, it easily pops up the menu for remove. But for the library i added, it's not 100%. it will pop up maybe, but when i try to repeatedly right click, it also MAY NOT show the menu for the remove library option.
> 
> So in the end i try to go into library, then go back, then try right click again.
> 
> Anyway that works (sort of)
> 
> *update
> 
> After i remove the library, then re add back, the remove option seems more reliable. Donno whats up with that, but this seems to work. probably can consider it fixed

I think this is due to the `Mark as read/unread` feature. Right now it performs some checks to determine how many pages there are in total and how many are marked as read (Most of this data is cached after it's retrieved the first time). On local files that calculation is fast, but over the network it can be slower. For now, I've changed it to run asynchronously so it doesn't affect the context menu ca51b122372c89b4414572b31f7bf05ac7800c22

> I can confirm in OpenComic Setup 1.6.2.master.b9cb5ea, I cannot open any files on 192.168.X.X INCLUDING IMAGE FOLDERS, EVERYTHING WILL BE FROZEN.

I found the cause of this error, the app was entering an infinite loop when checking the parent folder's labels to apply automatic label-based configurations. This fixes it 7ca4d200730d5b2814e24cad4b34969ab38a2857

Build: https://mega.nz/file/uChXgTIK#tPYXEuyk9bWfBl5HAWSP41AiepVkuKfaf0SQLisgh2M

**Comment by gsxgmpkt9020** [comment]
> > Just wanted to report, i can now remove the library i added, that was using the truenas guts location.
> > But it's weird. Because, right click the pepper default library, it easily pops up the menu for remove. But for the library i added, it's not 100%. it will pop up maybe, but when i try to repeatedly right click, it also MAY NOT show the menu for the remove library option.
> > So in the end i try to go into library, then go back, then try right click again.
> > Anyway that works (sort of)
> > *update
> > After i remove the library, then re add back, the remove option seems more reliable. Donno whats up with that, but this seems to work. probably can consider it fixed
> 
> I think this is due to the `Mark as read/unread` feature. Right now it performs some checks to determine how many pages there are in total and how many are marked as read (Most of this data is cached after it's retrieved the first time). On local files that calculation is fast, but over the network it can be slower. For now, I've changed it to run asynchronously so it doesn't affect the context menu [ca51b12](https://github.com/ollm/OpenComic/commit/ca51b122372c89b4414572b31f7bf05ac7800c22)
> 
> > I can confirm in OpenComic Setup 1.6.2.master.b9cb5ea, I cannot open any files on 192.168.X.X INCLUDING IMAGE FOLDERS, EVERYTHING WILL BE FROZEN.
> 
> I found the cause of this error, the app was entering an infinite loop when checking the parent folder's labels to apply automatic label-based configurations. This fixes it [7ca4d20](https://github.com/ollm/OpenComic/commit/7ca4d200730d5b2814e24cad4b34969ab38a2857)
> 
> Build: https://mega.nz/file/uChXgTIK#tPYXEuyk9bWfBl5HAWSP41AiepVkuKfaf0SQLisgh2M

Fatal errors in this new version.
![Image](https://github.com/user-attachments/assets/51ef6b18-1011-4141-a882-2b72b684c102)
![Image](https://github.com/user-attachments/assets/9d730103-849c-4001-91e7-63d51f5fb362)
![Image](https://github.com/user-attachments/assets/96ed3c6d-1d57-4667-8790-fe31c19947fb)

**Comment by ollm** [comment]
It seems the build wasn't done correctly and some files were missing, I tested the next build and it works properly.

Build: https://mega.nz/file/ePgkDbxK#7yF5KAOxtIZ44km94PHmoMfl_qt-c8KwHr7AixbBKjA

**Comment by mooglestiltzkin** [comment]
> It seems the build wasn't done correctly and some files were missing, I tested the next build and it works properly.
> 
> Build: https://mega.nz/file/ePgkDbxK#7yF5KAOxtIZ44km94PHmoMfl_qt-c8KwHr7AixbBKjA

just to report,

when i add library using

`\\GUTS\Storage\Pictures\Manga`

it adds it to library. it loads fast. and when i try open a comic that is zip/rar/7zip it will open and work. No freezing, it just works.

but there is still a error message

"error when unzipping: is not archive."


in my manga folder i tend to put

/manga/ manga title/ 

* within there arecompressed files and maybe some images for notes or some random pic thats not a compressed file 

so not sure but thats y that popped out?



i open the dev tool and the warnings where infinite generating. something seems terribly wrong

https://i.imgur.com/AAgLJoL.jpeg

**Comment by ollm** [comment]
> just to report,
> 
> when i add library using
> 
> `\\GUTS\Storage\Pictures\Manga`
> 
> it adds it to library. it loads fast. and when i try open a comic that is zip/rar/7zip it will open and work. No freezing, it just works.
> 
> but there is still a error message
> 
> "error when unzipping: is not archive."
> 
> in my manga folder i tend to put
> 
> /manga/ manga title/
> 
> * within there arecompressed files and maybe some images for notes or some random pic thats not a compressed file
> 
> so not sure but thats y that popped out?

This can happen when a compressed file is corrupted or is another type of file but has the extension of a compressed file (zip, cbz, etc.). I've made some changes so that when this message is displayed, the console will print the file causing it b0d9cfc4a2f16af0be5e26f478819c2e74899420. It should now appear something like this:

<img width="702" height="79" alt="Image" src="https://github.com/user-attachments/assets/380b68f4-b02b-4c22-9439-18676b68c388" />

> i open the dev tool and the warnings where infinite generating. something seems terribly wrong
> 
> https://i.imgur.com/AAgLJoL.jpeg

This isn't very important, it happens when the same file is read simultaneously from different parts of OpenComic (for example, when generating thumbnails and counting the number of pages, as these processes run separately). To prevent this, since in some cases it can cause errors or affect performance, I've made these changes cefa1c552309a27e04ec6c6c5b7d2549028eeed5

Build: https://mega.nz/file/fTA0mBxT#q1gZkUPKIAjtjMSaVTK-cdhUq-_JXarQzQmk7j_hvQ0

**Comment by mooglestiltzkin** [comment]
> This can happen when a compressed file is corrupted or is another type of file but has the extension of a compressed file (zip, cbz, etc.). I've made some changes so that when this message is displayed, the console will print the file causing it [b0d9cfc](https://github.com/ollm/OpenComic/commit/b0d9cfc4a2f16af0be5e26f478819c2e74899420). It should now appear something like this:


you are right. i installed the new build u link and tested dev debug, and it did just show 1 error rather than an infinite loop of errors.

found the file in question

`readCompressed | 7z (zip) | \\GUTS\Storage\Pictures\Manga\Gantz\Broken download\GANTZ_v03-7[xxxxxxxx]\GANTZ_v03[xxxxxx][hq]\Gantz_v03c23.zip: 159.93798828125 ms`


ok so i deleted the bad file. then i reloaded opencomic and tried again, no more errors.

yeah, i think the debug that reports the specific file and it doesn't do an infinite spam, this is MUCH MUCH better. actually helpful to find the issue and doesn't feel like it's gonna crash your pc cause the error previously was open ended.

Ty so much ollm.


Just a recap what we fixed in this thread so far

- library remove function fixed
- view an added library from a smb location (my case was from truenas zfs linux) no longer cause a freeze in the app
- debug no longer shows infinite looping bug error. in fact it now has the added feature of pointing out the specific file and it doesn't infinite spam the bug either. also after removing the problematic corrupt zip file, it works fine without any bugs showing in dev bugs.

overall assessment, seems quite stable and functional for the release update imho.



will this update be in a 1.6.4 or something?

**Comment by gsxgmpkt9020** [comment]
> will this update be

Of course will be

**Comment by ollm** [comment]
> you are right. i installed the new build u link and tested dev debug, and it did just show 1 error rather than an infinite loop of errors.
> 
> found the file in question
> 
> `readCompressed | 7z (zip) | \\GUTS\Storage\Pictures\Manga\Gantz\Broken download\GANTZ_v03-7[xxxxxxxx]\GANTZ_v03[xxxxxx][hq]\Gantz_v03c23.zip: 159.93798828125 ms`
> 
> ok so i deleted the bad file. then i reloaded opencomic and tried again, no more errors.
> 
> yeah, i think the debug that reports the specific file and it doesn't do an infinite spam, this is MUCH MUCH better. actually helpful to find the issue and doesn't feel like it's gonna crash your pc cause the error previously was open ended.

The error message should start with either `Error loading compressed file` or `Error when unzipping`.

The one you shared appears whenever OpenComic internally reads or extracts a compressed file, and it's used to show which files are being read or extracted and how long OpenComic takes to do it. In principle, it shouldn't indicate that the file itself has a problem, unless, for example, the same file keeps appearing in the console every time.

> will this update be in a 1.6.4 or something?

Yes, in version `v1.6.3`, if no more error reports come in over the next few days, I'll probably release it.

**Comment by ollm** [comment]
Closing this, since the fix is now available in [`v1.6.3`](https://opencomic.app/docs/installation/download)
